# Generated by Django 5.2.13 on 2026-04-23 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('turma', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_corretor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'turma', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=50)),
                ('arquivo_prova', models.FileField(blank=True, help_text='PDF da prova', null=True, upload_to='provas/')),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('numero_questoes', models.PositiveIntegerField(default=10)),
                ('alternativas_por_questao', models.PositiveIntegerField(default=5)),
                ('gabarito', models.JSONField(default=dict, help_text='Dicionário com número da questão e alternativa correta')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('encerrada', 'Encerrada')], default='rascunho', max_length=20)),
                ('is_manual', models.BooleanField(default=False, help_text='Se a prova foi criada manualmente no sistema')),
                ('is_online', models.BooleanField(default=False, help_text='Se a prova pode ser respondida online pelos alunos')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alunos', models.PositiveIntegerField(default=0)),
                ('media_notas', models.FloatField(default=0)),
                ('maior_nota', models.FloatField(default=0)),
                ('menor_nota', models.FloatField(default=0)),
                ('mediana_notas', models.FloatField(default=0)),
                ('desvio_padrao', models.FloatField(default=0)),
                ('taxa_aprovacao', models.FloatField(default=0)),
                ('questoes_estatisticas', models.JSONField(default=dict)),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='corretor_core.avaliacao')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aluno_nome', models.CharField(max_length=200)),
                ('turma', models.CharField(max_length=50)),
                ('respostas', models.JSONField(default=dict, help_text='Respostas do aluno')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('modo', models.CharField(choices=[('scanner', 'Scanner/QR Code'), ('online', 'Resposta Online')], default='scanner', max_length=20)),
                ('data_correcao', models.DateTimeField(auto_now_add=True)),
                ('imagem_original', models.ImageField(blank=True, null=True, upload_to='correcoes/')),
                ('observacoes', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='corretor_core.avaliacao')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-data_correcao'],
            },
        ),
        migrations.CreateModel(
            name='TokenQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('tipo', models.CharField(choices=[('prova', 'Token da Prova (acesso geral)'), ('aluno', 'Token Individual por Aluno')], default='prova', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('max_usos', models.PositiveIntegerField(default=1, help_text='Número máximo de usos (0 = ilimitado)')),
                ('usos_count', models.PositiveIntegerField(default=0)),
                ('ip_ultimo_uso', models.GenericIPAddressField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_qr', to='corretor_core.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_qr', to='corretor_core.avaliacao')),
            ],
            options={
                'verbose_name': 'Token QR',
                'verbose_name_plural': 'Tokens QR',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aluno_nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('conectado', 'Conectado'), ('iniciado', 'Iniciado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('desconectado', 'Desconectado')], default='conectado', max_length=20)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas', to='corretor_core.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='corretor_core.avaliacao')),
                ('token_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas', to='corretor_core.tokenqr')),
            ],
            options={
                'verbose_name': 'Tentativa',
                'verbose_name_plural': 'Tentativas',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['professor', 'status'], name='corretor_co_profess_c19e95_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['data_criacao'], name='corretor_co_data_cr_fab86f_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['avaliacao', 'data_correcao'], name='corretor_co_avaliac_3270cf_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['aluno_nome', 'turma'], name='corretor_co_aluno_n_282291_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['nota'], name='corretor_co_nota_b5e29e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenqr',
            index=models.Index(fields=['token', 'status'], name='corretor_co_token_77e705_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenqr',
            index=models.Index(fields=['avaliacao', 'status'], name='corretor_co_avaliac_9fec74_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativa',
            index=models.Index(fields=['avaliacao', 'status'], name='corretor_co_avaliac_9fb113_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativa',
            index=models.Index(fields=['ultima_atividade'], name='corretor_co_ultima__22e444_idx'),
        ),
    ]
