# Generated by Django 5.2.13 on 2026-05-26 01:12
# Modificado manualmente: AlunoITA usa SeparateDatabaseAndState porque a tabela
# alunos_sync pode já existir no banco (criada pelo sistema ITA externo).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor_core', '0002_delete_alunos_corretor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # AlunoITA: a tabela alunos_sync pode já existir (criada pelo sistema ITA).
        # Usamos SeparateDatabaseAndState para que o Django rastreie o model
        # sem tentar criar a tabela se ela já existir.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # CREATE TABLE IF NOT EXISTS — seguro mesmo se já existir
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS alunos_sync (
                            id          SERIAL PRIMARY KEY,
                            codigo      VARCHAR(20)  DEFAULT '',
                            nome        VARCHAR(200) NOT NULL,
                            turma       VARCHAR(100) NOT NULL,
                            turma_id    INTEGER,
                            curso       VARCHAR(200) DEFAULT '',
                            ativo       INTEGER      DEFAULT 1,
                            escola_id   INTEGER,
                            data_matricula DATE
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS alunos_sync;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AlunoITA',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('codigo', models.CharField(blank=True, max_length=20)),
                        ('nome', models.CharField(max_length=200)),
                        ('turma', models.CharField(max_length=100)),
                        ('turma_id', models.IntegerField(blank=True, null=True)),
                        ('curso', models.CharField(blank=True, max_length=200)),
                        ('ativo', models.IntegerField(default=1)),
                        ('escola_id', models.IntegerField(blank=True, null=True)),
                        ('data_matricula', models.DateField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'alunos_sync',
                        'ordering': ['nome'],
                        'managed': True,
                    },
                ),
            ],
        ),

        # DesempenhoAluno — nova tabela, criada normalmente
        migrations.CreateModel(
            name='DesempenhoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_nome', models.CharField(db_index=True, max_length=200, verbose_name='Nome do Aluno')),
                ('turma', models.CharField(db_index=True, max_length=100, verbose_name='Turma')),
                ('escola_id', models.IntegerField(db_index=True, default=0, verbose_name='ID da Escola (Tenant)')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Avaliações')),
                ('media_geral', models.FloatField(default=0, verbose_name='Média Geral')),
                ('maior_nota', models.FloatField(default=0, verbose_name='Maior Nota')),
                ('menor_nota', models.FloatField(default=0, verbose_name='Menor Nota')),
                ('taxa_aprovacao', models.FloatField(default=0, verbose_name='Taxa de Aprovação (%)')),
                ('evolucao', models.FloatField(default=0, verbose_name='Evolução (última − média inicial)')),
                ('classificacao', models.CharField(
                    choices=[
                        ('excelente', 'Excelente'),
                        ('satisfatorio', 'Satisfatório'),
                        ('em_desenvolvimento', 'Em Desenvolvimento'),
                        ('critico', 'Crítico'),
                    ],
                    default='em_desenvolvimento', max_length=20, verbose_name='Classificação'
                )),
                ('notas_por_disciplina', models.JSONField(default=dict, verbose_name='Notas por Disciplina')),
                ('historico_notas', models.JSONField(default=list, verbose_name='Histórico de Notas')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Desempenho do Aluno',
                'verbose_name_plural': 'Desempenhos dos Alunos',
                'ordering': ['turma', 'aluno_nome'],
                'indexes': [
                    models.Index(fields=['escola_id', 'turma'], name='corretor_co_escola__9d3d98_idx'),
                    models.Index(fields=['classificacao'], name='corretor_co_classif_7ae05d_idx'),
                ],
                'unique_together': {('aluno_nome', 'turma', 'escola_id')},
            },
        ),

        # ObservacaoPedagogica — nova tabela, criada normalmente
        migrations.CreateModel(
            name='ObservacaoPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_nome', models.CharField(db_index=True, max_length=200, verbose_name='Nome do Aluno')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma')),
                ('escola_id', models.IntegerField(db_index=True, default=0, verbose_name='ID da Escola (Tenant)')),
                ('tipo', models.CharField(
                    choices=[
                        ('elogio', '🌟 Elogio'),
                        ('atencao', '⚠️ Atenção'),
                        ('encaminhamento', '📋 Encaminhamento'),
                        ('informativo', 'ℹ️ Informativo'),
                    ],
                    default='informativo', max_length=20, verbose_name='Tipo'
                )),
                ('conteudo', models.TextField(verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('editado_em', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('professor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='observacoes_pedagogicas',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Professor',
                )),
            ],
            options={
                'verbose_name': 'Observação Pedagógica',
                'verbose_name_plural': 'Observações Pedagógicas',
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['escola_id', 'aluno_nome', 'turma'], name='corretor_co_escola__3a25c4_idx'),
                ],
            },
        ),
    ]
