# Generated by Django 5.2.13 on 2026-04-23 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gamificaedu_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='gamificaedu_core.tenant'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
