# Generated by Django 5.2.14 on 2026-05-17 00:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('escola', models.CharField(max_length=200, verbose_name='Escola')),
                ('serie', models.CharField(max_length=50, verbose_name='Série/Ano')),
                ('nivel_experiencia', models.CharField(choices=[('iniciante', 'Iniciante — nunca mexi com eletrônica'), ('basico', 'Básico — já vi alguma coisa'), ('intermediario', 'Intermediário — já programei um pouco')], max_length=20, verbose_name='Nível de experiência')),
                ('turno', models.CharField(choices=[('manha', 'Manhã (8h–12h)'), ('tarde', 'Tarde (13h–17h)')], max_length=10, verbose_name='Turno')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do responsável')),
                ('cpf_responsavel', models.CharField(max_length=14, verbose_name='CPF do responsável')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('certificado_emitido', 'Certificado Emitido')], default='pendente', max_length=30)),
                ('codigo_inscricao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=199.0, max_digits=8)),
                ('id_transacao_pag', models.CharField(blank=True, max_length=200)),
                ('referencia_pag', models.CharField(blank=True, max_length=200)),
                ('certificado_gerado', models.BooleanField(default=False)),
                ('data_certificado', models.DateTimeField(blank=True, null=True)),
                ('autoriza_imagem', models.BooleanField(default=False, verbose_name='Autoriza uso de imagem')),
                ('aceita_termos', models.BooleanField(default=False, verbose_name='Aceita os termos')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
            },
        ),
    ]
