# Generated by Django 5.2.17 on 2026-09-26 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alter_inscricao_valor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Formação em Inteligência Artificial Aplicada à Educação', max_length=200, verbose_name='Nome do curso')),
                ('edicao', models.CharField(help_text='Ex.: 2026.2 (Nov–Dez/2026)', max_length=50, verbose_name='Edição')),
                ('carga_horaria_total', models.PositiveIntegerField(default=120, verbose_name='Carga horária total (h)')),
                ('carga_horaria_ead', models.PositiveIntegerField(default=96, verbose_name='Carga horária EAD (h)')),
                ('carga_horaria_presencial', models.PositiveIntegerField(default=24, verbose_name='Carga horária presencial (h)')),
                ('periodo_ead_descricao', models.CharField(default='Novembro (trilha online)', max_length=200, verbose_name='Período EAD')),
                ('periodo_presencial_descricao', models.CharField(default='Dezembro (imersão presencial + projeto final)', max_length=200, verbose_name='Período presencial')),
                ('local_presencial', models.CharField(default='Itapipoca, Ceará', max_length=200, verbose_name='Local da etapa presencial')),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=99.9, max_digits=8, verbose_name='Valor da inscrição')),
                ('vagas_total', models.PositiveIntegerField(default=40, verbose_name='Vagas totais')),
                ('frequencia_minima_pct', models.PositiveIntegerField(default=75, verbose_name='Frequência mínima (%)')),
                ('nota_minima', models.DecimalField(decimal_places=1, default=6.0, max_digits=3, verbose_name='Nota mínima')),
                ('peso_prova_presencial_pct', models.PositiveIntegerField(default=40, verbose_name='Peso — prova/projeto presencial (%)')),
                ('peso_atividades_modulo_pct', models.PositiveIntegerField(default=20, verbose_name='Peso — atividades por módulo (%)')),
                ('peso_participacao_pct', models.PositiveIntegerField(default=10, verbose_name='Peso — participação (%)')),
                ('peso_projeto_final_pct', models.PositiveIntegerField(default=30, verbose_name='Peso — projeto aplicado final (%)')),
                ('certificacao_descricao', models.CharField(default='Certificado de Extensão/Aperfeiçoamento, mediante 75% de frequência e aproveitamento mínimo (nota final ≥ 6,0)', max_length=300, verbose_name='Descrição da certificação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Aceita novas inscrições')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formação em IA — Edição',
                'verbose_name_plural': 'Formação em IA — Edições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaFormacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('instituicao_ensino', models.CharField(max_length=200, verbose_name='Instituição onde leciona')),
                ('area_disciplina', models.CharField(max_length=150, verbose_name='Área / disciplina que leciona')),
                ('tempo_docencia', models.CharField(choices=[('menos_1', 'Menos de 1 ano'), ('1_3', 'De 1 a 3 anos'), ('4_10', 'De 4 a 10 anos'), ('mais_10', 'Mais de 10 anos')], max_length=20, verbose_name='Tempo de docência')),
                ('declara_atuacao_docente', models.BooleanField(default=False, verbose_name='Declara atuação na docência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('certificado_emitido', 'Certificado Emitido')], default='pendente', max_length=30)),
                ('codigo_matricula', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=99.9, max_digits=8)),
                ('id_transacao_pag', models.CharField(blank=True, max_length=200)),
                ('referencia_pag', models.CharField(blank=True, max_length=200)),
                ('frequencia_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência (%)')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota final')),
                ('projeto_final_titulo', models.CharField(blank=True, max_length=300, verbose_name='Título/link do projeto final')),
                ('observacoes_staff', models.TextField(blank=True, verbose_name='Observações internas')),
                ('certificado_gerado', models.BooleanField(default=False)),
                ('data_certificado', models.DateTimeField(blank=True, null=True)),
                ('autoriza_imagem', models.BooleanField(default=False, verbose_name='Autoriza uso de imagem')),
                ('aceita_termos', models.BooleanField(default=False, verbose_name='Aceita os termos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='inscricoes.formacaoia')),
            ],
            options={
                'verbose_name': 'Matrícula — Formação em IA',
                'verbose_name_plural': 'Matrículas — Formação em IA',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='ModuloFormacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do módulo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('formato', models.CharField(max_length=200, verbose_name='Formato')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga horária (h)')),
                ('fundamentacao_texto', models.TextField(blank=True, verbose_name='Fundamentação teórica')),
                ('fundamentacao_referencias', models.JSONField(blank=True, default=list, verbose_name='Referências')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='inscricoes.formacaoia')),
            ],
            options={
                'verbose_name': 'Módulo — Formação em IA',
                'verbose_name_plural': 'Módulos — Formação em IA',
                'ordering': ['curso', 'numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SessaoFormacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('carga_horaria', models.PositiveIntegerField(default=4, verbose_name='Carga horária (h)')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('conteudo', models.JSONField(blank=True, default=list, verbose_name='Conteúdo')),
                ('metodologia', models.CharField(blank=True, max_length=300, verbose_name='Metodologia')),
                ('exemplo_pratico', models.TextField(blank=True, verbose_name='Exemplo prático')),
                ('recursos', models.JSONField(blank=True, default=list, verbose_name='Recursos')),
                ('avaliacao_produto', models.CharField(blank=True, max_length=300, verbose_name='Produto avaliativo')),
                ('referencias', models.JSONField(blank=True, default=list, verbose_name='Referências')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='inscricoes.moduloformacaoia')),
            ],
            options={
                'verbose_name': 'Sessão — Formação em IA',
                'verbose_name_plural': 'Sessões — Formação em IA',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PresencaFormacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Dia 1 — Fundamentos de IA e Educação'), (2, 'Dia 2 — Robótica, Cultura Maker e IA na Prática'), (3, 'Dia 3 — Apresentação do Projeto Final')], verbose_name='Dia do curso')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('hora_chegada', models.TimeField(blank=True, null=True, verbose_name='Hora de chegada')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('registrado_por', models.CharField(blank=True, max_length=100, verbose_name='Registrado por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='inscricoes.matriculaformacaoia', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Presença — Formação em IA',
                'verbose_name_plural': 'Presenças — Formação em IA',
                'ordering': ['dia', 'matricula__nome_completo'],
                'unique_together': {('matricula', 'dia')},
            },
        ),
    ]
