# Generated by Django 5.2.13 on 2026-05-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamificaedu_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='gamificaedu_quiz.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_por_questao', models.IntegerField(default=30, help_text='Segundos por questão')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_criados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificaedu_core.tenant')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='gamificaedu_quiz.quiz'),
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='gamificaedu_quiz.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-concluido_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('alternativa_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamificaedu_quiz.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificaedu_quiz.questao')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='gamificaedu_quiz.resultadoquiz')),
            ],
        ),
    ]
