# Generated by Django 5.2.13 on 2026-04-23 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamificaedu_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='PlanoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('trial', 'Trial (7 dias)'), ('professor', 'Professor — R$29/mês'), ('escola', 'Escola — R$99/mês')], default='trial', max_length=20)),
                ('inicio', models.DateField(default=django.utils.timezone.now)),
                ('vencimento', models.DateField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado')], default='trial', max_length=20)),
                ('pagseguro_code', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_escola', to='gamificaedu_core.tenant')),
            ],
            options={
                'verbose_name': 'Plano da Escola',
                'verbose_name_plural': 'Planos das Escolas',
            },
        ),
        migrations.CreateModel(
            name='SessaoSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=600, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_sso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão SSO',
                'verbose_name_plural': 'Sessões SSO',
                'ordering': ['-criada_em'],
            },
        ),
    ]
