# Generated by Django 5.2.13 on 2026-04-23 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamificaedu_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('gamificacao', 'Gamificação'), ('qrcode', 'QR Code'), ('avaliacao', 'Avaliação'), ('recurso', 'Recurso')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='repositorio/pdfs/', verbose_name='Arquivo PDF')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificaedu_core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
